name: pdf_viewer_example
version: 1.0.0+2

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
   
  
  flutter:
    sdk: flutter
  
  http: ^0.12.2
  file_picker: ^4.6.1
  flutter_pdfview:
  lottie: ^1.3.0
  path: ^1.7.0
  path_provider: 
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/pdf.png"

flutter:
  uses-material-design: true


  assets:
    - assets/.
