name: pdf_viewer_example
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.0
  file_picker: ^2.1.6
  flutter:
    sdk: flutter
  flutter_pdfview: ^1.0.4
  http: ^0.12.2
  lottie: ^1.3.0
  path: ^1.7.0
  path_provider: ^1.6.27
  google_fonts: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/pdf.png"

flutter:
  uses-material-design: true


  assets:
    - assets/.
